### ISSUE TITLE
Relationship to upstream sig project with similar name?

### ISSUE THREAD

**Issue by webframp** [bsycorp/kind#12]
Hey there, this is a useful tool thanks!

Since they're similarly named, I was just curious about any connection to https://github.com/kubernetes-sigs/kind or if they're remain completely distinct projects?

Thanks again.

**Comment by nhoughto** [comment]
Not related but ended up with the same acronym.

We had ours first so really they should change 😒, assume they won’t tho 😞, any suggestions for a new name?

**Comment by webframp** [comment]
Hah, naming isn’t too critical for me. Their “kind” seems more like local workflow tooling, we find yours is good to use in our ci pipeline for integration tests. 

Just helps to know the relationship clearly.
