### ISSUE TITLE
Better support for kubectl running in a container

### ISSUE THREAD

**Issue by igorgatis** [bsycorp/kind#13]
Many already use a container as development environment. In my case, I invoke kubectl from a container. While using kind, I had to build it with `STATIC_IP=$(docker-machine ip)` so that x509 certificate includes value of `STATIC_IP`. Then I had to fix `.kube/config` to point to `server: https://$STATIC_IP:8443` instead of `server: https://localhost:8443` as `localhost` means something else inside of a container. Those steps are no big deal but breaks "_a kubernetes cluster in 30s_" experience.

When using vanialla image (e.g. `bsycorp/kind:latest-1.13`) it is very common to get an IP which is not the same used during build time. For instance, it often gets `172.17.0.4` which causes the error: `Unable to connect to the server: x509: certificate is valid for 172.30.99.1, 127.0.0.1, 172.17.0.2, 10.96.0.1, 10.0.0.1, not 172.17.0.4`. In my case, it is mandatory to build kind passing `STATIC_IP`.

In the perfect world, I'd use vanilla image `bsycorp/kind:latest-1.13` passing a container name. Then `/config` endpoint would produce entries for `localhost` and the passed container name. Then the last missing piece would be to make Docker resolve the container by name since default bridge network does not provide IP resolution by container name. Perhaps using a custom network suffices. This would bring kind to a "_a kubernetes cluster in 30s **that just works**!_" experience.

**Comment by igorgatis** [comment]
I managed to get by the static IP restriction I described above, here is how:

```
docker network create kubenet

docker run -d -it --privileged --name=kubernetes --net=kubenet \
  -p 8443:8443 -p 10080:10080 bsycorp/kind:v1.11.5

sleep 30

docker network connect kubenet $HOSTNAME
mkdir ~/.kube
curl http://kubernetes:10080/config | sed 's/localhost/kubernetes/g' > ~/.kube/config
```

Then one can run:
```
kubectl get all --all-namespaces
```

**Comment by nhoughto** [comment]
Hmm not quite sure I understand your workflow properly, so you are running `kind` in a container, and you are dev'ing in another container? and want to `kubectl` from dev container to `kind` container seamlessly?

I can imagine you would have x509 problems. `kind` is build to be used from the host (port forwarded from host to container, so is localhost), or via a pod-style network (addressable via localhost). So from kubectl POV its always talking to localhost.

The reason for the `STATIC_IP` shenanigans is that the container IP that `kind` builds with before we push it to dockerhub is dynamic, and then the container IP it runs with when you start it up is again dynamic and likely different to the first IP, so `kind` uses the `STATIC_IP` to sidestep all this dynamic behaviour and forces a constant value throughout the build and run phase. It isn't the intention of that value to be used outside the `kind` container itself.

Would an adequate workaround be disabling x509 validation in kubectl? That way you can continue your workflow without adding complexity? Is generally just for testing so might not be a big deal? 😬

**Comment by igorgatis** [comment]
We have a rather perculiar setup: each developer has a Windows 10 pro laptop.

We run our bootstrap script which installs docker toolbox and a bunch of other tools using chocolatey. It also produces our development environment script (devenv.sh) which creates (if needed) a boot2docker VM in Virtualbox.

The same script also creates a volume and starts a couple of containers: a samba server container and a another container with all development tools. It then attaches to this last container. New invokations to this script attaches new bash sessions to the tooling container.

This tooling container connects to dockerd socket. We control everything from it. Life is great while using docker, docker compose and even docker swarm. We recently decide to go kubernetes and that's when I tried kind.

We tried hard to replace docker machine with minikube. Minikube feels like old, buggy, feature lacking version of docker machine. It is sad.

After the "solution" I posted above, I came across the challenge of exposing a service in kind to the tooling container. I'm still rewiring my brain around docker in docker networking. Any help would be appreciated.

**Comment by nhoughto** [comment]
Yeah that is an interesting setup, you mention using `docker-machine` and finding problems with `minikube` both of which i've had problems with in the past.

But docker for windows is supposed to be better and supports kube otb? Have you tried that?
https://docs.docker.com/docker-for-windows/#kubernetes

I know kube on docker for mac is pretty great. Feels a bit like fighting the framework to try and re-purpose `kind` as a full solution to local workflow problems, likely you will keep hitting issues like exposing services, overlay network, dns changes etc etc etc. Kube is a complex beast, you want to stay as close to stock as possible..

**Comment by nhoughto** [comment]
Bump for this, otherwise will close :+1:
