### ISSUE TITLE
NodeHasDiskPressure

### ISSUE THREAD

**Issue by derba** [bsycorp/kind#15]
My issue is somewhat similar to this one: https://github.com/ubuntu/microk8s/issues/29

Kind had worked quite fine for a while. I had installed tons of helm charts, life was happy. Then once after starting a pod it did not come up. `kubectl get pods` showed Evicted status. `kubectl describe node minikube` was confusing.

```
...
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests     Limits
  --------           --------     ------
  cpu                1655m (41%)  2 (50%)
  memory             1464Mi (4%)  8682Mi (27%)
  ephemeral-storage  0 (0%)       0 (0%)
Events:
  Type     Reason                Age    From               Message
  ----     ------                ----   ----               -------
  Warning  EvictionThresholdMet  4m32s  kubelet, minikube  Attempting to reclaim ephemeral-storage
  Normal   NodeHasDiskPressure   4m23s  kubelet, minikube  Node minikube status is now: NodeHasDiskPressure
```

The host looks fine, `df` does not show anything suspicious.
I issued `docker exec kind docker system prune -f` and voila, everything went back normal. I am pretty happy again. Still, do you have any suggestions?

**Comment by nhoughto** [comment]
How are you using it? In a CI process or just advoc to running things in a local workflow?

Never had a problem with docker running out of space, but we really just use it for CI integration testing.

**Comment by derba** [comment]
I am using kind on my laptop for toying.

**Comment by nhoughto** [comment]
Ah ok we’ve really only tested it for ephemeral CI processes where a cluster is spun up quickly and things deployed, tested and shutdown. Haven’t really tried a less ephemeral use case.

If you have steps to reproduce the problem and possible solutions, happy to consider tweaks to scripts, sounds like you are using kind outside the scope of its purpose? Happy to consider changes if it helps your use case 👍🏼

**Comment by derba** [comment]
I think I know what lead to the issue. I played with local Persistent Volume. And that must have remnants left. Docker prune on the *host* cleaned up the mess.
