### ISSUE TITLE
Bug in Travis config

### ISSUE THREAD

**Issue by moltar** [bsycorp/kind#17]
I think this line should tag the image with 14? Right now it overwrites 13...

https://github.com/bsycorp/kind/blob/db034784104e310a0c661169ba04f1ec6c0fa902/.travis.yml#L12

**Comment by moltar** [comment]
While at it, maybe a good idea to update README to the latest version too:

https://github.com/bsycorp/kind/blob/master/README.md#quickstart

I was stuck on 1.10 and was not sure why certain things weren't working 😁

**Comment by nhoughto** [comment]
Ah yes good pickups, fixed in latest.

**Comment by moltar** [comment]
build is failing btw
