### ISSUE TITLE
Use an IP in the private ranges

### ISSUE THREAD

**Issue by carlpett** [bsycorp/kind#2]
Hi!
As per the README, you set a static IP of 172.99.99.1. This IP is not part of the private range, but is actually an IP assigned to Rackspace. You should be using one of the [private address ranges](https://tools.ietf.org/html/rfc1918) instead, for example in 172.16.0.0-172.31.255.255.

**Comment by nhoughto** [comment]
Yep, much better idea, just picked one at random. I’ll change it.
