### ISSUE TITLE
Minikube 1.10.1 & K8s 1.18 Support

### ISSUE THREAD

**Issue by stiller-leser** [bsycorp/kind#33]
Hi,

I just tried to get it to run with K8s v1.18.2, however as you mentioned in a different issue, Minikube seems to have changed a lot. Any ideas already, what changes would be needed?

I am looking to K8s 1.18 since I need `VolumeSnapshot` and `VolumeSnapshotContent` to be available.

Best regards,
stiller-leser

**Comment by stiller-leser** [comment]
Created first issue with Minikube here: https://github.com/kubernetes/minikube/issues/8273

**Comment by stiller-leser** [comment]
Setup seems to work with Minikube 1.9.2 - if https://github.com/bsycorp/kind/blob/master/resources/setup.sh#L71 is renamed to `kubeadm.yaml.new` due to https://github.com/kubernetes/minikube/commit/16a8c386821dbba82296b9437f0071a19f882554

**Comment by nhoughto** [comment]
pushed changes to support minikube 1.15 and kube 1.19
