### ISSUE TITLE
How to build image for v0.8.1

### ISSUE THREAD

**Issue by ricfeatherstone** [bsycorp/kind#36]
I'm trying to run kind using podman. I see experimental support was added to v0.8.0 and am trying to build an image from v0.8.1 by running `make quick` in the `images/base` dir but this looks to required a script outside the repo.

Is there an experimental image publicly available I could use or some help I could get to build the image?

**Comment by nhoughto** [comment]
Doubt it, your question is really can you run DinD in pod man, KinD just builds on top of that.

**Comment by ricfeatherstone** [comment]
That was my original question then I found this which talks about podman support. https://github.com/kubernetes-sigs/kind/releases/tag/v0.8.0
I changed the issue to ask for help building an image for this tag so I can see if it meets my needs. Can we reopen this issue for this question or should I open a new one?

**Comment by nhoughto** [comment]
Yeah sigs kind and this kind aren't the same thing, named the same but totally diff projects.

**Comment by ricfeatherstone** [comment]
Apologies, I should have spotted that.
I'm using the operator-sdk which scaffolds molecule tests using this kind image.
To confirm, if dind supports podman, this will support it

**Comment by nhoughto** [comment]
should do*

haven't tested it, never used podman and its not on my radar? but maybe? 🤷‍♂️
