### ISSUE TITLE
Update the docs for how to use bsycorp/kind with Docker Executor using Gitlab CI

### ISSUE THREAD

**Issue by mlai-ata** [bsycorp/kind#38]
Was looking into how to get this to work with Gitlab CI using Docker Executor today.

What has to happen is if you use bsycorp/kind using a service, with the Docker Executor, is your endpoints aren't bound to localhost, they're bound to whatever you called the image.

For ex. if you specified the service image as bsycorp/kind:latest-1.17, your kubernetes-ready endpoint is at http://bsycorp-kind:10080/kubernetes-ready, not localhost. 

https://docs.gitlab.com/runner/executors/docker.html#network-per-build contains the official documentation for how service endpoints work with the Docker Executor.

**Comment by nhoughto** [comment]
done
