### ISSUE TITLE
Cannot query from kubectl running inside kubectl container

### ISSUE THREAD

**Issue by SkylerLutz** [bsycorp/kind#47]
Hi! I run `kubectl` out of a container and I'm having trouble reaching the cluster created by `kind`. Interestingly, all of these come back with `200 OK`:

```
http://localhost:10080/docker-ready 
http://localhost:10080/kubernetes-ready 
http://localhost:10080/config 
```

However, when I run `podman run --rm --name kubectl -v /home/${USER}/.kube/config:/root/.kube/config myrepo/kubectl:latest kubectl get ns`, the command hangs and eventually times out. 

```
Unable to connect to the server: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

I also tried running `podman` with the `--network podman` flag, with no luck. 

I noticed that if I change the IP in `~/.kube/config` from 172.30.99.1 to localhost, and run `kubectl` outside of the container ... `kubectl get ns` works. So I think it has something to do with the network... any ideas? Thanks in advance!

**Comment by nhoughto** [comment]
Hmm no experience with podman, but i'd guess this is a simple networking issue? the kubectl container will have different networking than outside the container (unless run with host networking..) so the IP in the kube config is likely wrong.

depending how you run `kind` you likely need to change the IP that the kube config points at for it to work, it might be on localhost, or not.. depends how you run it. For example if you run `kind` as a pod inside kubernetes it will be addressed by the pod ip, not localhost or 172.30...

**Comment by SkylerLutz** [comment]
@nhoughto I'd agree it's most likely a simple networking issue. Is there any way to connect to the `kind` cluster using the default IP (172.30.99.1) so I don't have to set the kube config to localhost? I tried running `kubectl` in a container with host networking, and I also tried running `kubectl` directly (on my host, outside a container entirely) and saw the same timeout issue as above. For some reason, the default IP `172.30.99.1` is just not reachable... I also tried running `kind` with host networking but that failed to initialize.

**Comment by nhoughto** [comment]
the intent is you don't use `172.30.99.1` at all, its just an internal concern to do the cluster setup ahead of time. On startup the `kind` instance itself (either running in docker or kubernetes itself) should be given an IP, the intent is to use that IP, the pod ip or container ip. And address is that way, not via `172.30.99.1` or `localhost`
