### ISSUE TITLE
Comparison with kubernetes-sigs/kind

### ISSUE THREAD

**Issue by mitar** [bsycorp/kind#5]
From a link in your README, it seems that option 2 has moved to https://github.com/kubernetes-sigs/kind which now looks very similar to this repo? I would be curious about any comparison between these two projects?

**Comment by nhoughto** [comment]
Good question, it looks like kube testing sig is now tackling this problem, they even used the same name 😒 ! I'll have to have a play and see if it solves the same problem. Thanks for the tip.

**Comment by nhoughto** [comment]
So I had a look at the other `kind`, it looks pretty similar but slightly different goals, it is obviously in the beginning stages and the TODO list captures what is missing (docs, lots of configuration options etc). 

This image is built to start fast for CI with a prebuilt cluster and preloaded images, the other `kind` doesn't appear to specifically cater to spinning back up a prebuilt cluster (i think? some network trickery is required), but it does have a preloaded image capability. So you could use the other kind to achieve a similar goal but it would take a bit longer to start, more of a replacement to `kubeadm-dind-cluster.sh`. It also only supports 1.11+ and adds a overlay network (weave) by default.

So different enough for this project to continue, I guess will need to think of a new name though as I expect they aren't going to change theirs 😬

**Comment by ensonic** [comment]
Fun, I also file a bug for the other kind to disambiguate.
