### ISSUE TITLE
Kind cluster fails to startup as the certificates in /var/lib/localkube/certs is expired

### ISSUE THREAD

**Issue by itsnagaraj** [bsycorp/kind#52]
Kind container wont start as the client certificate in `/etc/kubernetes/kubelet.conf` has expired. Rebuilding and pushing images to docker hub will fix the issue. Images were last published a year ago

```
E1027 04:03:09.952574    5879 bootstrap.go:265] part of the existing bootstrap client certificate in /etc/kubernetes/kubelet.conf is expired: 2023-10-26 09:41:59 +0000 UTC
E1027 04:03:09.952611    5879 server.go:302] "Failed to run kubelet" err="failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory"
```

@nhoughto can you please help us with re-running the pipeline? Not sure if the cert can be automatically renewed if it has expired which would be better option though

**Comment by nhoughto** [comment]
Pushed a refreshed v 23, does that solve the problem?

**Comment by itsnagaraj** [comment]
Thanks @nhoughto. Newer images has solved the problem. Thanks for your help

**Comment by albertrajan** [comment]
Hi @nhoughto - can you please refresh certs for 1.18.7 version as well?

**Comment by albertrajan** [comment]
https://github.com/bsycorp/kind/issues/53 raised since this issue is closed.
