### ISSUE TITLE
Kind cluster fails to startup as client cert in /etc/kubernetes/kubelet.conf has expired - please refresh for v1.18.7

### ISSUE THREAD

**Issue by albertrajan** [bsycorp/kind#53]
Duplicate of issue https://github.com/bsycorp/kind/issues/52, but requesting cert refresh on v1.18.7

**Comment by albertrajan** [comment]
Hi @nhoughto please can you help this request. Thanks.

**Comment by nhoughto** [comment]
done

**Comment by albertrajan** [comment]
Awesome! Thanks :).
