### ISSUE TITLE
A question regarding certificates

### ISSUE THREAD

**Issue by brosenan** [bsycorp/kind#6]
I'm trying to see if this container can be used for CI. The kind-travis-example project provides just a small part of it (creating a container and waiting for Kubernetes to come up).I t
I tried to take it a bit further in a fork of that project:

https://github.com/brosenan/kind-travis-example/blob/master/.travis.yml

Unfortunately, I'm getting the following error when trying to use kubectl against Kind:
$ kubectl get ns
Unable to connect to the server: x509: certificate is valid for 172.30.99.1, 172.17.0.2, 10.96.0.1, 10.0.0.1, not 127.0.0.1

(see https://travis-ci.com/brosenan/kind-travis-example/builds/87872206 for the complete log)

I tried to understand, from the code, how the certificate is created, and saw it was created by minikube. When using Kind on my machine (tried on both Linux and MacOS), the certificate accepts 127.0.0.1/localhost.

- What could be the reason for it not to accept localhost inside Travis?
- How should I configure kubectl so that I can connect to it?

Thanks,
Boaz.

**Comment by nhoughto** [comment]
I’ll have a look and get back to you 👍🏼

**Comment by nhoughto** [comment]
So this is how we are doing it, your approach of using the config directly is nicer tho, can probably enhance it to make it work. As an interim this works:

```
# setup kubectl
wget http://127.0.0.1:10080/ca.crt
wget http://127.0.0.1:10080/client.crt
wget http://127.0.0.1:10080/client.key

# localhost / sml.place are the same, but kubectl needs localhost as thats what the cert has
kubectl config set-cluster minikube-cluster --server=https://127.0.0.1:8443 \
    --insecure-skip-tls-verify=true

kubectl config set-credentials minikube-admin \
    --certificate-authority=ca.pem \
    --client-key=client.key \
    --client-certificate=client.crt

kubectl config set-context minikube --cluster=minikube-cluster --user=minikube-admin
kubectl config use-context minikube
kubectl config set-context $(kubectl config current-context) --namespace=default
```

**Comment by nhoughto** [comment]
Ok made some updates to kind and the example to show how to do it, and it works.

https://github.com/bsycorp/kind-travis-example/blob/master/.travis.yml

Thanks for the feedback and idea, can simplify our setup now too 👍

**Comment by brosenan** [comment]
Thanks 👍
